services:
  webapp:
    image: ris-norms-app:001
    container_name: webapp
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres17:5432/risnorms
      - SPRING_PROFILES_ACTIVE=local,local-docker
    depends_on:
      postgres17:
        condition: service_healthy
    volumes:
      - ./local-storage:/app/.local-storage
    ports:
      - "8080:8080"

  postgres17:
    extends:
      file: docker-compose-services.yaml
      service: postgres17

volumes:
  postgres17-data:
