services:
  nginx:
    build:
      context: .
      dockerfile: DockerfileNginxPlaywright
    ports:
      - 8080:8080
    depends_on:
      - webapp
  webapp:
    image: ris-norms-app:001
    build:
      context: .
      dockerfile: DockerfileApp
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres15:5432/risnorms
      - REDIS_HOST=redis
      - SPRING_PROFILES_ACTIVE=local
    depends_on:
      - postgres15
      - redis
  postgres15:
    image: postgres:15-alpine
    restart: always
    container_name: postgres15
    volumes:
      - postgres15-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=risnorms
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d risnorms"]
      interval: 5s
      retries: 3
      start_period: 5s
      timeout: 3s
  redis:
    image: cgr.dev/chainguard/redis:latest
    extra_hosts:
      - localhost:host-gateway
    container_name: redis
    command:
      - "--maxmemory 256mb"
      - "--maxmemory-policy allkeys-lru"
      - "--timeout 300"
      - "--tcp-keepalive 10"
      - "--user redis on +@all -CONFIG ~* >password"
      - "--user default off resetchannels -@all"
    ports:
      - "6379:6379"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "redis-cli -h 127.0.0.1 --user redis -a password PING | grep 'PONG' || exit 1",
        ]
      interval: 5s
      retries: 5
      start_period: 3s
      timeout: 5s

volumes:
  postgres15-data:
