services:
  postgres14:
    image: postgres:14-alpine
    restart: always
    container_name: postgres14
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
