services:
  traefik:
    image: traefik:v2.9
    container_name: traefik
    volumes:
      - ./traefik.yaml:/etc/traefik/config.yml:ro
    command:
      - "--api.dashboard=false"
      - "--providers.file.filename=/etc/traefik/config.yml"
    ports:
      - 80:80

  backend:
    build:
      context: ./
      dockerfile: DockerfileApp
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres14:5432/risnorms
    ports:
      - :8080
    depends_on:
      - postgres14
      - traefik

  frontend:
    build:
      context: ./frontend
    ports:
      - :8080
    depends_on:
      - traefik

  postgres14:
    image: postgres:14-alpine
    restart: always
    container_name: postgres14
    volumes:
      - postgres14-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=risnorms
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d risnorms"]
      interval: 5s
      retries: 3
      start_period: 5s
      timeout: 3s

volumes:
  postgres14-data:
