sentry:
  environment: uat
  traces-sample-rate: 0.01
  max-request-body-size: always
  send-default-pii: on

spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver # database interceptor needed for Sentry
    url: jdbc:p6spy:postgresql://${database.host}:${database.port:5432}/${database.database}?currentSchema=${database.schema}

otc:
  obs:
    everkuendung:
      bucket-name: ris-norms-uat-ev-ldml-data
    public:
      bucket-name: ris-norms-uat-public-ldml-data
    private:
      bucket-name: ris-norms-uat-private-ldml-data
