spring:
  # Database Configuration
  datasource:
    url: jdbc:postgresql://${database.host:localhost}:${database.port:5432}/${database.database:risnorms}
    username: ${database.username:test}
    password: ${database.password:test}
    driver-class-name: org.postgresql.Driver

# expose health endpoint
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health
  endpoint:
    health:
      enabled: true
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState,db
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true

#logging:
#  level:
#    org.springframework: DEBUG
