spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/risnorms?currentSchema=norms
    username: test
    password: test
  flyway:
    locations: classpath:db/migration,classpath:db/data/real,classpath:db/data/synthetic,classpath:db/data/e2e
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8443/realms/ris

frontend:
  auth:
    url: http://localhost:8443
    realm: ris
    clientId: ris-norms-local

otc:
  obs:
    private:
      bucket-name: private
    public:
      bucket-name: public
    prototype:
      bucket-name: prototype
    everkuendung:
      bucket-name: everkuendung

sentry:
  environment: local

everkuendung:
  certificate:
    path: file:../local/certs/certificate.pem

local:
  file-storage: .local-storage
