spring:
  # Database Configuration
  datasource:
    url: jdbc:postgresql://${database.host:localhost}:${database.port:5432}/${database.database:risnorms}?currentSchema=${database.schema:norms}
    username: ${database.user:test}
    password: ${database.password:test}
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    baseline-version: 0.0
    locations: ${flyway.locations:classpath:db/migration}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# expose health endpoint
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      enabled: true
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState,db
    prometheus:
      enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true

sentry:
  exception-resolver-order: -2147483647
  ignored-exceptions-for-type: org.springframework.web.method.annotation.HandlerMethodValidationException, org.springframework.web.bind.MethodArgumentNotValidException, org.springframework.web.context.request.async.AsyncRequestNotUsableException, de.bund.digitalservice.ris.norms.application.exception.ActiveModDestinationNormNotFoundException, de.bund.digitalservice.ris.norms.application.exception.LdmlDeNotValidException, de.bund.digitalservice.ris.norms.application.exception.LdmlDeSchematronException, de.bund.digitalservice.ris.norms.application.exception.NormExistsAlreadyException, de.bund.digitalservice.ris.norms.application.exception.NormNotFoundException, de.bund.digitalservice.ris.norms.application.exception.RegelungstextNotFoundException, de.bund.digitalservice.ris.norms.application.exception.NotAXmlFileException, de.bund.digitalservice.ris.norms.application.exception.ValidationException, de.bund.digitalservice.ris.norms.application.exception.NotLdmlDeXmlFileException, de.bund.digitalservice.ris.norms.application.exception.NormWithGuidAlreadyExistsException

otc:
  obs:
    endpoint: https://obs.eu-de.otc.t-systems.com

publish:
  cron: "0 0 2 * * 1-5" # # Runs at 2:00 AM UTC (3:00 AM Berlin time in CET)
