spring:
  # Database Configuration
  datasource:
    url: jdbc:postgresql://${database.host}:${database.port}/${database.database}?currentSchema=${database.schema}
    username: ${database.user}
    password: ${database.password}
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    baseline-version: 0.0
    locations: ${flyway.locations}
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${oauth2.issuer-uri}
  mvc:
    static-path-pattern: /app/**

# expose health endpoint
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      enabled: true
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState,db
    prometheus:
      enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true

org:
  jobrunr:
    background-job-server:
      enabled: true
    miscellaneous:
      allow-anonymous-data-usage: false

sentry:
  exception-resolver-order: -2147483647
  ignored-exceptions-for-type: org.springframework.web.method.annotation.HandlerMethodValidationException, org.springframework.web.bind.MethodArgumentNotValidException, org.springframework.web.context.request.async.AsyncRequestNotUsableException, de.bund.digitalservice.ris.norms.application.exception.LdmlDeNotValidException, de.bund.digitalservice.ris.norms.application.exception.LdmlDeSchematronException, de.bund.digitalservice.ris.norms.application.exception.NormExistsAlreadyException, de.bund.digitalservice.ris.norms.application.exception.NormNotFoundException, de.bund.digitalservice.ris.norms.application.exception.RegelungstextNotFoundException, de.bund.digitalservice.ris.norms.application.exception.NotAXmlFileException, de.bund.digitalservice.ris.norms.application.exception.NotLdmlDeXmlFileException, de.bund.digitalservice.ris.norms.application.exception.NormWithGuidAlreadyExistsException

otc:
  obs:
    endpoint: https://obs.eu-de.otc.t-systems.com

publish:
  cron: "0 0 22 * * 0-4" # Runs at 10:00 PM UTC, which is 11:00 PM Berlin time in CET (Winter) So-Th and 12:00 AM in CEST (Summer) Mo-Fr
  portal-prototype:
    cron: "0 0 3 * * *" # Runs at 03:00 PM UTC, which is 04:00 AM Berlin time in CET (Winter) and 5:00 AM in CEST (Summer) every day

frontend:
  auth:
    url: ${oauth2.frontend-url}
    realm: ${oauth2.realm}
    clientId: ${oauth2.client-id}
