spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/risnorms?currentSchema=norms
    username: test
    password: test
  flyway:
    locations: classpath:db/migration,classpath:db/data
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8443/realms/ris

local:
  file-storage: .local-storage

frontend:
  auth:
    url: http://localhost:8443
    realm: ris
    clientId: ris-norms-local

otc:
  obs:
    private:
      bucket-name: private
      access-key-id: test
      secret-access-key: test
    public:
      bucket-name: public
      access-key-id: test
      secret-access-key: test
