spring:
  # Database Configuration
  datasource:
    url: jdbc:postgresql://${database.host:localhost}:${database.port:5432}/${database.database:risnorms}
    username: ${database.user:test}
    password: ${database.password:test}
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    baseline-version: 0.0
    locations: ${flyway.locations:classpath:db/migration}
  data:
    redis:
      host: ${redis.host:localhost}
      username: ${redis.user:redis}
      password: ${redis.password:password}
server:
  servlet:
    session:
      cookie:
        same-site: lax
        max-age: 43200 # 12*60*60

# expose health endpoint
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      enabled: true
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState,db,redis
    prometheus:
      enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true

sentry:
  exception-resolver-order: -2147483647
