spring:
  flyway:
    locations: classpath:db/migration,classpath:db/data
  security:
    oauth2:
      client:
        registration:
          oidcclient:
            client-id: ris-norms-local
            client-secret: ris-norms-local
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/ris
            authorization-uri: http://localhost:8443/realms/ris/protocol/openid-connect/auth

local:
  file-storage: .local-storage
#logging:
#  level:
#    org.springframework: DEBUG
