sentry:
  environment: production
  traces-sample-rate: 0.01
  max-request-body-size: always
  send-default-pii: on

publish:
  enabled: false
  portal-prototype:
    enabled: true

spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver # database interceptor needed for Sentry
    url: jdbc:p6spy:postgresql://${database.host}:${database.port:5432}/${database.database}?currentSchema=${database.schema}

otc:
  obs:
    everkuendung:
      bucket-name: ris-norms-prod-ev-ldml-data
    public:
      bucket-name: ris-norms-prod-public-ldml-data
    private:
      bucket-name: ris-norms-prod-private-ldml-data
    prototype:
      bucket-name: ris-norms-prod-prototype-ldml-data

everkuendung:
  certificate:
    path: file:/etc/certs/certificate.pem
