spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver # database interceptor needed for Sentry
    url: jdbc:p6spy:postgresql://${database.host}:${database.port:5432}/${database.database}?currentSchema=${database.schema}

sentry:
  environment: local

local:
  file-storage: .local-storage

otc:
  obs:
    private:
      bucket-name: private
      access-key-id: test
      secret-access-key: test
    public:
      bucket-name: public
      access-key-id: test
      secret-access-key: test
    everkuendung:
      bucket-name: everkuendung
      access-key-id: test
      secret-access-key: test
