spring:
  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/risnorms
    username: test
    password: test
    driver-class-name: org.postgresql.Driver

# expose health endpoint
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health
  endpoint:
    health:
      enabled: true

#logging:
#  level:
#    org.springframework: DEBUG
