spring:
  security:
    oauth2:
      client:
        registration:
          oidcclient:
            provider: keycloak
            scope:
              - openid
              - profile
              - email
