spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/risnorms?currentSchema=norms
    username: test
    password: test
  flyway:
    locations: classpath:db/migration,classpath:db/data/real,classpath:db/data/synthetic,classpath:db/data/e2e

otc:
  obs:
    private:
      bucket-name: private
    public:
      bucket-name: public
    prototype:
      bucket-name: prototype

sentry:
  environment: local

local:
  file-storage: .local-storage
