spring:
  # Database Configuration
  datasource:
    url: jdbc:postgresql://${database.host}:${database.port}/${database.database}?currentSchema=${database.schema}
    username: ${database.user}
    password: ${database.password}
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    baseline-version: 0.0
    locations: ${flyway.locations}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${oauth2.issuer-uri}

# expose health endpoint
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      enabled: true
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState,db
    prometheus:
      enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true

sentry:
  exception-resolver-order: -2147483647
  ignored-exceptions-for-type: org.springframework.web.method.annotation.HandlerMethodValidationException, org.springframework.web.bind.MethodArgumentNotValidException, org.springframework.web.context.request.async.AsyncRequestNotUsableException, de.bund.digitalservice.ris.norms.application.exception.LdmlDeNotValidException, de.bund.digitalservice.ris.norms.application.exception.LdmlDeSchematronException, de.bund.digitalservice.ris.norms.application.exception.NormExistsAlreadyException, de.bund.digitalservice.ris.norms.application.exception.NormNotFoundException, de.bund.digitalservice.ris.norms.application.exception.RegelungstextNotFoundException, de.bund.digitalservice.ris.norms.application.exception.NotAXmlFileException, de.bund.digitalservice.ris.norms.application.exception.NotLdmlDeXmlFileException, de.bund.digitalservice.ris.norms.application.exception.NormWithGuidAlreadyExistsException

otc:
  obs:
    endpoint: https://obs.eu-de.otc.t-systems.com

publish:
  cron: "0 0 23 * * 0-4" # Runs at 11:00 PM UTC, which is 12:00 AM Berlin time in CET (Winter) and 1:00 AM in CEST (Summer) Mo-Fr

frontend:
  auth:
    url: ${oauth2.frontend-url}
    realm: ${oauth2.realm}
    clientId: ${oauth2.client-id}
