name: Bi-weekly checking of backend libraries for missing updates

on:
  schedule:
    # cron: "minute hour dayOfMonth month dayOfWeek"
    # 7am Berlin in winter (8am Berlin time in summer) on the 1st and 15th of every month
    - cron: "0 6 1,15 * *"
  # also: allow to run this workflow manually
  workflow_dispatch:

jobs:
  backend-determine-library-updates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@5188e9b5527a0a094cee21e2fe9a8ca44b4629af
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "21.0"
          distribution: "temurin"
          cache: gradle
      - name: Run gradle versionCatalogUpdate
        working-directory: ./backend
        run: ./gradlew versionCatalogUpdate
      - name: "Setup jq"
        uses: dcarbone/install-jq-action@v2
      - name: Determine library updates
        working-directory: ./backend
        run: |
          if [ `jq .outdated.count  build/dependencyUpdates/report.json` -ne 0 ]; then
            echo "Outdated libraries found. Cf. above for details."
            exit 1
          else
            echo "No outdated libraries found"
          fi
      - name: Send status to Slack
        uses: digitalservicebund/notify-on-failure-gha@15dd05b628141b7bac0ad26e08c1935cb3ba6bc8 # v1.4.0
        if: ${{ failure() && github.ref == 'refs/heads/main' }}
        with:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
