on:
  workflow_call:

jobs:
  validate-gradle-wrapper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@85cde3f5a1033b2adc2442631c24b530f1183a1a

  e2e-tests:
    needs: [validate-gradle-wrapper]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get Gradle version
        working-directory: ./backend
        run: |
          echo "GRADLE_VERSION=$(sed -n 's/.*gradle-\([0-9]*\(\.[0-9]*\)*\)-.*/\1/p' ./gradle/wrapper/gradle-wrapper.properties)" >> $GITHUB_ENV
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "21.0"
          distribution: "temurin"
      - uses: gradle/gradle-build-action@e1ada08a9a43fad9770411d5dd099f25ece2569d
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}
          arguments: bootRun
          build-root-directory: ./backend
      # - name: Send status to Slack
      #   uses: digitalservicebund/notify-on-failure-gha@15dd05b628141b7bac0ad26e08c1935cb3ba6bc8
      #   if: ${{ failure() && github.ref == 'refs/heads/main' }}
      #   with:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}