on:
  workflow_call:
    inputs:
      browser:
        required: false
        type: string
        default: chromium

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
#    container:
#      image: mcr.microsoft.com/playwright:v1.44.1-jammy
#      options: --ipc=host
    steps:
      - uses: actions/checkout@v4
      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v3
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "21.0"
          distribution: "temurin"
          cache: gradle
      - name: Start PostgreSQL
        run: docker compose up --detach postgres14 redis
      - name: Start backend in the background (via .gradlew and nohup)
        run: nohup ./gradlew bootRun > /tmp/nohup.out &
        working-directory: ./backend
      - name: Wait for backend to start
        run: |
          while [ `grep -c 8080 /tmp/nohup.out` -lt 1 ] ;
          do
          echo "sleeping for 1 second"
          sleep 1
          done
        working-directory: ./backend
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ./frontend/.node-version
          cache: npm
          cache-dependency-path: ./frontend/package-lock.json
      - name: Cache npm cache
        uses: actions/cache@v4
        id: cache-npm-cache
        with:
          # The docs discourage caching `node-modules`, cf. https://github.com/actions/cache/blob/main/examples.md#node---npm
          path: /home/runner/.npm
          key: npm-cache-${{ hashFiles('./frontend/package-lock.json') }}
      - name: Install node modules
        run: npm ci
        working-directory: ./frontend
      - name: Get Playwright version
        working-directory: ./frontend
        run: echo "PLAYWRIGHT_VERSION=$(jq -r '.packages["node_modules/@playwright/test"].version' package-lock.json)" >> $GITHUB_ENV
      - name: Cache browser binaries
        id: cache-browser-binaries
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}-${{ inputs.browser }}
      - name: Cache WebKit system dependencies
        id: cache-webkit-deps
        if: inputs.browser == 'webkit'
        uses: actions/cache@v4
        with:
          path: /usr/lib/x86_64-linux-gnu/
          key: ${{ runner.os }}-webkit-deps-${{ env.PLAYWRIGHT_VERSION }}
      - name: Install system dependencies for WebKit
        if: inputs.browser == 'webkit' && steps.cache-webkit-deps.outputs.cache-hit != 'true'
        run: npx playwright install-deps
      - name: Install playwright browsers
        if: steps.cache-browser-binaries.outputs.cache-hit != 'true'
        run: |
          npx --yes playwright install --with-deps ${{ inputs.browser }}
        working-directory: ./frontend
      - name: Run e2e tests in ${{ inputs.browser }} against localhost
        env:
          E2E_BASE_URL: "http://localhost:5173"
          TZ: 'Europe/Berlin'
        run: |
          echo "Running e2e tests 1 time"

          npm run dev &
          DEV_PID=$!
          npm run test:e2e -- --project ${{ inputs.browser }} --repeat-each 1
          pkill -P $DEV_PID
        working-directory: ./frontend
      - name: Upload screenshots and traces of failed tests
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: failed-e2e-tests-${{ inputs.browser }}
          path: |
            ./frontend/test-results/**/*.png
            ./frontend/test-results/**/trace.zip
      - name: Upload test result blobs reports
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: test-results-blob-e2e-${{ inputs.browser }}
          path: ./frontend/blob-report/test-report.zip
          retention-days: 1
      - name: Send status to Slack
        uses: digitalservicebund/notify-on-failure-gha@9ced11eb82275ff563398657c140caba3a9e6ec1
        if: ${{ failure() && github.ref == 'refs/heads/main' }}
        with:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
