name: "Release VSCode Extension if changed"

on:
  push:
    # branches: [main]
    paths:
      - 'vscode-extension/**'
  pull_request:
    # branches: [main]
  # Allow to run this workflow manually
  workflow_dispatch:

jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      - run: "Workflow triggered"
