name: Scan

on:
  schedule:
    - cron: "0 6 * * *" # Every day at 8am
  # Allow to run this workflow manually
  workflow_dispatch:

jobs:
  reset-trivy-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Remove all caches and database of the trivy scanner
        uses: aquasecurity/trivy-action@22d2755f774d925b191a185b74e782a4b0638a41
        env:
          TRIVY_RESET: true
        with:
          scan-type: "fs"
      - name: Download trivy vulnerabilities DB
        uses: aquasecurity/trivy-action@22d2755f774d925b191a185b74e782a4b0638a41
        env:
          TRIVY_DOWNLOAD_DB_ONLY: true
        with:
          scan-type: "fs"
      - name: Download trivy Java index DB
        uses: aquasecurity/trivy-action@22d2755f774d925b191a185b74e782a4b0638a41
        env:
          TRIVY_DOWNLOAD_JAVA_DB_ONLY: true
        with:
          scan-type: "fs"

  build-time-machine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "17.0"
          distribution: "temurin"
      - name: Setup Gradle
        uses: gradle/gradle-build-action@87a9a15658c426a54dd469d4fc7dc1a73ca9d4a6
        with:
          gradle-version: ${{ env.GRADLE_VERSION}}
          arguments: build
          build-root-directory: ./time-machine
      - name: Send status to Slack
        uses: digitalservicebund/notify-on-failure-gha@15dd05b628141b7bac0ad26e08c1935cb3ba6bc8
        if: ${{ failure() }}
        with:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  trivy-scan:
    runs-on: ubuntu-latest
    needs: [reset-trivy-cache, build-time-machine]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@22d2755f774d925b191a185b74e782a4b0638a41
        with:
          scan-type: 'fs'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH' #ignored by sarif report
      - name: Check trivy results
        run: |
          if grep -qE 'HIGH|CRITICAL' trivy-results.sarif; then
            echo "Vulnerabilities found"
            exit 1
          else
            echo "No significant vulnerabilities found"
            exit 0
          fi
      - name: Upload Trivy scan results to GitHub Security tab
        if: ${{ always() && github.ref == 'refs/heads/main' }} # Bypass non-zero exit code..
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
      - name: Send status to Slack
        # Third-party action, pin to commit SHA!
        # See https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions
        uses: digitalservicebund/notify-on-failure-gha@15dd05b628141b7bac0ad26e08c1935cb3ba6bc8 # v1.4.0
        if: ${{ failure() && github.ref == 'refs/heads/main' }}
        with:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
